services:
  waf:
    build:
      context: .
      dockerfile: ./waf/Dockerfile
    container_name: waf
    ports:
      - "8080:8080"
    depends_on:
      - gateway
      - frontend
    environment:
      - BACKEND=http://gateway:8081
      - FRONTEND=http://frontend:80
    networks:
      - microservices
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - microservices
    depends_on:
      - gateway

  main_service:
    build: ./backend/main_service
    container_name: main-service
    environment:
      HOSTNAME: main-service
      HOST_IP: main-service
      MARIADB_DATABASE: ${MARIADB_MAIN_DATABASE}
      MARIADB_USER: ${MARIADB_MAIN_USER}
      MARIADB_PASSWORD: ${MARIADB_MAIN_PASSWORD}
      DATABASE_URL: mysql://${MARIADB_MAIN_USER}:${MARIADB_MAIN_PASSWORD}@main_service_db:3306/${MARIADB_MAIN_DATABASE}
      HOST: 0.0.0.0
      FRONTEND_URL: http://localhost:8080
      BACKEND_URL: http://localhost:8080/api/main
      QUIZ_SERVICE_URL: http://quiz_service:3001/
      AI_SERVICE_URL: http://ai_service:3002/
      RAG_SERVICE_URL: http://rag_service:3003/
      CALLBACK_URL: http://localhost:8080/api/main/auth/google/callback
      PORT: 3000
    networks:
      - microservices
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      main_service_db:
        condition: service_healthy
  quiz_service:
    build: ./backend/quiz_service
    container_name: quiz_service
    environment:
      HOSTNAME: quiz_service
      HOST_IP: quiz_service
      MARIADB_DATABASE: ${MARIADB_QUIZ_DATABASE}
      MARIADB_USER: ${MARIADB_QUIZ_USER}
      MARIADB_PASSWORD: ${MARIADB_QUIZ_PASSWORD}
      DATABASE_URL: mysql://${MARIADB_QUIZ_USER}:${MARIADB_QUIZ_PASSWORD}@quiz_service_db:3306/${MARIADB_QUIZ_DATABASE}
      HOST: 0.0.0.0
      FRONTEND_URL: http://localhost:8080
    networks:
      - microservices
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      quiz_service_db:
        condition: service_healthy
###
  ai_service:
    build: ./backend/ai_services/ai_service
    container_name: ai_service
    environment:
      HOSTNAME: ai_service
      HOST_IP: ai_service
      FRONTEND_URL: http://localhost:8080
    networks:
      - microservices
    env_file:
      - .env
    ports:
      - "3002:3002"

  rag_service:
    build: ./backend/ai_services/rag_service
    container_name: rag_service
    environment:
      HOSTNAME: rag_service
      HOST_IP: rag_service
      FRONTEND_URL: http://localhost:8080
      OLLAMA_HOST: http://ollama_service:11434

    networks:
      - microservices
    env_file:
      - .env
    ports:
      - "3003:3003"
    depends_on:
      - ollama_service
  ollama_service:
    build: ./backend/ai_services/ollama_service
    container_name: ollama_service
    environment:
      HOSTNAME: ollama_service
      HOST_IP: ollama_service
    networks:
      - microservices
    env_file:
      - .env
    ports:
      - "11434:11434"
##
  gateway:
    build: ./backend/gateway
    container_name: api-gateway
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - microservices
